function var_names = checkpoint_var_names()
% Checkpoint fields that must be persisted by BPSO_unified.m.
var_names = { ...
    'phase','seed_pool','seed_pool_cr', ...
    'record','record_time', ...
    'x','v','xm','ym','fxm','fym', ...
    'n_right','CR_worst','loss_mse', ...
    'particle_time_sec','iter','num', ...
    'cache_bits','cache_n_right','cache_CR_worst','cache_loss_mse', ...
    'cache_CR_each','cache_F_soft','cache_worst_idx','cache_is_full', ...
    'stage2_target_iter','stall_gen','fym_prev', ...
    'p_eda','best_CR_each','best_worst_idx','init_reeval_queue'};
end
