function refresh_parallel_worker_code()
%REFRESH_PARALLEL_WORKER_CODE Force workers to reload updated attached files.
clear('append_path_once', ...
      'close_lumerical_worker_session', ...
      'LumericalWorkerSession', ...
      'make_eval_result', ...
      'make_lumerical_worker_session', ...
      'open_lumerical_mode', ...
      'set_slot', ...
      'softmin_score', ...
      'train_out', ...
      'worker_eval_particle');
rehash;
end
